### ISSUE TITLE
Remove or implement baseline arg in eval_task.py

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#102] opened 2019-11-26 18:53 UTC
https://github.com/JamesOwers/midi_degradation_toolkit/blob/703885761088d315bec29718dcd8ba46a6834b69/baselines/eval_task.py#L53

**Comment by apmcleod** [comment] 2019-11-27 00:52
Closing as duplicate of #85

**Closed by apmcleod** 2019-11-27 00:52 UTC
